_target_: src.ours.maple_reg.MAPLERegressor

# Fixed MAPLE parameters (not searched)
n_agents: 3
exploration_coef: 0.5
bandit_type: ucb
use_rf_style: true

# Searchable parameters in param_grid
param_grid:
  # Tree parameters
  min_samples_split: ${range:2, 17}
  min_samples_leaf: ${range:1, 17}

  # MAPLE-specific parameters to search (tuned for regression)
  feature_subset_ratio: [0.6, 0.8, 1.0]
  diversity_weight: [0.05, 0.1, 0.15]
  val_bandit_ratio: [0.15, 0.25]
  ema_alpha: [0.15, 0.25]
  prior_update_rate: [0.05, 0.1]
