_target_: src.baselines.xgb_cls.CustomXGBClassifier

param_grid:
  min_child_weight: ${range:1, 11}
  subsample: ${linspace:0.5, 1.0, 5}
  colsample_bylevel: ${linspace:0.5, 1.0, 5}
  colsample_bytree: ${linspace:0.5, 1.0, 5}
  colsample_bynode: ${linspace:0.5, 1.0, 5}
